language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 7.0.19
    - php: 7.0.19
      env: setup=lowest

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - vendor/bin/phpunit
  - '! find . -type f -name "*.php" ! -path "./vendor/*" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'